Feat: 로그인 기능 추가 및 환경변수 설정
Donggrina/Frontend pull request #38
Opened 2024-05-31 16:08 UTC by DHyeon98

## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호
#19 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 로그인 기능 추가되었습니다.
- 환경변수 설정하였으니 .env.local에 추가 바랍니다.

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-06-01 06:02 UTC, D5ng commented on components/login/kakao-button/kakao-button.tsx
> +  const kakaoURL = `${process.env.NEXT_PUBLIC_API_URL}/oauth2/authorization/kakao`;
환경변수와 관련된 것들은 config  폴더에서 관리하는게 좋아요.
이름만으로 여기서 관리를 하고있구나 유추할 수 있고, 컴포넌트 내부에 작성한게 아니기 때문에 리랜더링 관련된 문제도 없습니다. (여기서는 상관 없어보이긴 합니다)

2024-06-01 06:04 UTC, forestream requested changes
👍 깃헙 액션 오류를 제거해야 하겠군요

2024-06-01 06:04 UTC, forestream commented on components/login/kakao-button/kakao-button.tsx
Link 대신 이벤트 핸들러로 이동하신 이유가 궁금해요~

2024-06-01 09:18 UTC, DHyeon98 commented on components/login/kakao-button/kakao-button.tsx
사실 Link 태그가 다른 도메인으로 이동 불가능한줄 알았습니다..
수정하겠습니다!

2024-06-02 07:20 UTC, mun-jihye approved these changes

2024-06-02 07:21 UTC, mun-jihye commented
.env.local에 저장해야하는 변수 알려주세요!

2024-06-03 05:18 UTC, gaeaeg approved these changes

2024-06-03 05:20 UTC, merged